### ISSUE TITLE
Please rebase to latest ESP8266 driver

### ISSUE THREAD

**Issue by JanneKiiskila** [d-kato/esp32-driver#2]
There's been a significant amount of bug fixes to Mbed OS [ESP8266 driver](https://github.com/ARMmbed/mbed-os/blob/mbed-os-5.10/components/wifi/esp8266-driver/ESP8266Interface.cpp#L579-L586), please rebase to those.
Please implement also the get_default_instance() support (though it should come with the same rebase).

(By default this should be an on-going effort, i.e. keep up with the fixes in the future as well).

**Comment by d-kato** [comment]
@JanneKiiskila, I'm so sorry. I thought I replied, but I didn't.
The "get_default_instance()" has been supported. The ESP32 driver passed Mbed OS Socket test.(https://github.com/d-kato/esp32-driver/issues/4)

**Comment by JanneKiiskila** [comment]
Excellent, thank you very much!
