### ISSUE TITLE
UART packets being missed by AT parser

### ISSUE THREAD

**Issue by alejandrosklar** [d-kato/esp32-driver#5]
I'm experiencing serious issues using UART to interpret AT commands with this library. Has anyone else experienced this? I'm using an ESP32 wroom32 module, and have flashed the most recent esp32-at firmware.

For example, when scanning for networks, the "OK" command is usually received, but the AT parser does not begin waiting to recv it until after it has been received, thus leading to Timeout (this happens on about 75% of scans I perform). See debug output below:

`AT< +CWAP:(0,"linkys",-84,"0:13:10:87:5:06",6)`
`AT< OK`
`AT(Timeout)`
`AT? OK%n`

When I probe the TX/RX (uart1) lines with a separate FTDI cable and terminal while the program is running, I can see all the correct messages coming out of the module perfectly, but many times AT commands these same commands are not even received by the cmd parser, leading to very unreliable operation.

In my mbed config, EN and IO0 are both "NC", and I have tried with and without UART flow control (by defining the CTS/RTS pins and defining DEVICE_SERIAL_FC to 1). HW_flow_control seems to do nothing, as the program runs exactly the same regardless of if I actually connect the wires. And yes, when using Flow control, I do also update the ESP32-AT.bin firmware.

I feel like the SetTimeout() values and possibly mutexes are leading to serious  async issues. When initially using default values in the library, I had a ton of Timeout issues, pretty much with every command. Increasing the timeouts significantly improved performance, but still very unreliable. 

Any thoughts would be much appreciated. Happy to provide more info upon request.

**Comment by d-kato** [comment]
If the limit value of the scan function is smaller than the actual result obtained, it will time out. The delay when a timeout occurs is 510 ms.
Certainly, the scan function has been updated as it is not a good design. https://github.com/d-kato/esp32-driver/commit/2d5a0ccb114dde231c12224c0006179f9fef8ec6
